name: Ejecutar Pruebas Vitest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pruebas:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Instalar dependencias
      run: npm install
      
    - name: Ejecutar pruebas
      run: npm run test:run